openapi: 3.0.3
info:
  title: openapi
  version: v1
servers:
  - url: http://localhost:8080/api/v1
paths: {}

components:
  requestBodies:
    FileRequest:
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/FileDTO'
    FileArrayRequest:
      required: true
      content:
        multipart/form-data:
          schema:
            $ref: '#/components/schemas/FileArrayDTO'
  responses:
    FileResponse:
      description: FileResponse
      content:
        '*/*':
          schema:
            type: string
            format: binary
  schemas:
    FileArrayDTO:
      type: object
      properties:
        file:
          type: array
          items:
            type: string
            format: binary
    FileDTO:
      type: object
      properties:
        file:
          type: string
          format: binary